---
- name: Create new directories for Zabbix Agent
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ za_dir_conf_d }}"
    - "{{ za_dir_scripts }}"

- name: Download new Zabbix Agent zip archive
  win_get_url:
    url: "{{ za_download_url }}"
    dest: "{{ za_dir }}"
  register: za_new_download

- name: Unzip downloaded archive
  win_unzip:
    src: "{{ za_new_download.dest }}"
    dest: '{{ za_dir }}\inst_tmp\'
    delete_archive: yes
  register: za_unzipped
  when: za_new_download.status_code == 200

- name: Copy Zabbix Agent binaries
  win_copy:
    src: '{{ za_dir }}\inst_tmp\bin\zabbix_agentd.exe'
    dest: '{{ za_exe }}'
    remote_src: yes

- name: Create Zabbix Agent config file from template
  win_template:
    src: zabbix_agentd.conf.j2
    dest: '{{ za_conf }}'

- name: Install new Zabbix Agent service
  win_service:
    name: '{{ za_svc_name }}'
    path: '"{{ za_exe }}" --config "{{ za_conf }}"'
    display_name: '{{ za_svc_name }}'
    description: 'Provides system monitoring (deployed by Ansible)'
    state: started

- name: Remove temporary directory
  win_file:
    path: '{{ za_dir }}\inst_tmp\'
    state: absent
